<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Edit</strong> media' => '',
    '<strong>Add</strong> new gallery' => '<strong>Dodaj</strong> novu galeriju',
    '<strong>Confirm</strong> delete gallery' => '<strong>Potvrdi</strong> brisanje galerije',
    '<strong>Confirm</strong> delete item' => '<strong>Potvrdi</strong> brisanje stavke',
    '<strong>Edit</strong> gallery' => '<strong>Uredi</strong> galeriju',
    '<strong>Gallery</strong> ' => '<strong>Galerija</strong> ',
    '<strong>Gallery</strong> settings' => '<strong>Galerija</strong> -postavke',
    '<strong>List</strong> of galleries' => '<strong>Lista</strong> galerija',
    'Add Gallery' => 'Dodaj galeriju',
    'Adds gallery module to this space.' => 'Dodaje modul galerije ovom prostoru.',
    'Adds gallery module to your profile.' => 'Dodaje modul galerije vašem profilu.',
    'Back to overview' => 'Povratak na pregled',
    'Choose snippet gallery' => 'Odaberi galeriju isječka',
    'Click here to add new Gallery' => 'Klikni ovdje da dodaš novu galeriju',
    'Click or drop files here' => 'Ovdje kliknite ili pustite datoteke',
    'Close' => 'Zatvori',
    'Delete' => 'Obriši',
    'Delete Gallery' => 'Obriši galeriju',
    'Deleted' => 'Obrisano',
    'Do you really want to delete this gallery with all related content?' => 'Želite li zaista izbrisati ovu galeriju sa svim povezanim sadržajima?',
    'Do you really want to delete this item with all related content?' => 'Želite li stvarno izbrisati ovu stavku sa svim povezanim sadržajem?',
    'Don\'t show the gallery snippet in this space.' => 'Nemoj prikazati isječak galerije u ovom prostoru.',
    'Download' => 'Preuzimanje',
    'Edit' => 'Uredi',
    'Edit Gallery' => 'Uredi galeriju',
    'Gallery' => 'Galerija',
    'Gallery:' => 'Galerija:',
    'In case the gallery is not visible for the current user, the snippet will use the latest accessible gallery instead.' => 'U slučaju da galerija nije vidljiva za trenutačnog korisnika, isječak će umjesto njega upotrijebiti najnoviju dostupnu galeriju.',
    'Insufficient rights to execute this action.' => 'Nedovoljna razina prava za izvršenje.',
    'Item could not be deleted!' => 'Stavku nije moguće obrisati!',
    'Latest Gallery - {title} ({visibility})' => 'Zadnja galerija - {title} ({visibility})',
    'Make this gallery public' => 'Učini ovu galeriju javnom',
    'Media' => 'Medij',
    'Open Gallery' => 'Otvori galeriju',
    'Posted Media Files' => 'Objavljenje medijske datoteke',
    'Posted pictures' => 'Objavljenje slike',
    'Save' => 'Spremi',
    'Settings' => 'Postavke',
    'Show connected post' => 'Prikaži povezanu objavu',
    'Size:' => 'Veličina:',
    'There are no galleries available for this space. In order to configure the gallery snippet, please <a href="{createLink}">create</a> a new gallery' => 'Nema dostupnih galerija za ovaj prostor. Kako bi konfigurirali isječak galerije, molimo <a href="{createLink}">kreriraj</a> novu galeriju',
    'This gallery contains all posted media files from the profile.' => 'Ova galerija sadrži sve objavljene medija datoteke s profila.',
    'This gallery contains all posted media files from the space.' => 'Ova galerija sadrži sve objavljene medija datoteka iz prostora.',
    'This gallery contains all posted media.' => 'Ova galerija sve objavljene medije.',
    'This gallery contains all posted pictures.' => 'Ova galerija sadrži sve objavljene slike.',
    'Upload' => 'Učitaj',
    'added by ' => 'dodano od',
    'of posted media files' => 'objavljenih medijskih datoteka',
];
