<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> new gallery' => '',
    '<strong>Confirm</strong> delete gallery' => '',
    '<strong>Confirm</strong> delete item' => '',
    '<strong>Edit</strong> gallery' => '',
    '<strong>Edit</strong> media' => '',
    '<strong>Gallery</strong> ' => '',
    '<strong>Gallery</strong> settings' => '',
    '<strong>List</strong> of galleries' => '',
    'Gallery write access' => '',
    'Allows the user to add, modify images and galleries.' => '',
    'Add Gallery' => '',
    'Adds gallery module to this space.' => '',
    'Adds gallery module to your profile.' => '',
    'Back to overview' => '',
    'Choose snippet gallery' => '',
    'Click here to add new Gallery' => '',
    'Click or drop files here' => '',
    'Close' => '',
    'Delete' => '',
    'Delete Gallery' => '',
    'Deleted' => '',
    'Do you really want to delete this gallery with all related content?' => '',
    'Do you really want to delete this item with all related content?' => '',
    'Don\'t show the gallery snippet in this space.' => '',
    'Download' => '',
    'Edit' => '',
    'Edit Gallery' => '',
    'Gallery' => '',
    'Gallery:' => '',
    'In case the gallery is not visible for the current user, the snippet will use the latest accessible gallery instead.' => '',
    'Insufficient rights to execute this action.' => '',
    'Item could not be deleted!' => '',
    'Latest Gallery - {title} ({visibility})' => '',
    'Make this gallery public' => '',
    'Media' => '',
    'Open Gallery' => '',
    'Posted Media Files' => '',
    'Posted pictures' => '',
    'Save' => '',
    'Settings' => '',
    'Show connected post' => '',
    'Size:' => '',
    'There are no galleries available for this space. In order to configure the gallery snippet, please <a href="{createLink}">create</a> a new gallery' => '',
    'This gallery contains all posted media files from the profile.' => '',
    'This gallery contains all posted media files from the space.' => '',
    'This gallery contains all posted media.' => '',
    'This gallery contains all posted pictures.' => '',
    'Upload' => '',
    'added by ' => '',
    'of posted media files' => '',
];
