<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '<strong>Add</strong> new gallery' => 'Neue Galerie <strong>anlegen</strong>',
  '<strong>Confirm</strong> delete gallery' => 'Löschen der Galerie <strong>bestätigen</strong>',
  '<strong>Confirm</strong> delete item' => 'Löschen des Elements <strong>bestätigen</strong>',
  '<strong>Edit</strong> gallery' => 'Galerie <strong>bearbeiten</strong>',
  '<strong>Edit</strong> media' => 'Medien <strong>bearbeiten</strong>',
  '<strong>Gallery</strong> ' => '<strong>Galerie</strong>',
  '<strong>Gallery</strong> settings' => '<strong>Galerie</strong>-Einstellungen',
  '<strong>List</strong> of galleries' => 'Galerien-<strong>Liste</strong>',
  'Gallery write access' => '',
  'Allows the user to add, modify images and galleries.' => '',
  'Add Gallery' => 'Galerie hinzufügen',
  'Adds gallery module to this space.' => 'Fügt diesem Space das Galerie-Modul hinzu.',
  'Adds gallery module to your profile.' => 'Fügt deinem Profil das Galerie-Modul hinzu.',
  'Back to overview' => 'Zurück zur Übersicht',
  'Choose snippet gallery' => 'Galerie-Schnipsel auswählen',
  'Click here to add new Gallery' => 'Hier klicken, um eine neue Galerie hinzuzufügen',
  'Click or drop files here' => 'Hier klicken oder Dateien per Drag &amp; Drop platzieren',
  'Close' => 'Schließen',
  'Delete' => 'Löschen',
  'Delete Gallery' => 'Galerie löschen',
  'Deleted' => 'Gelöscht',
  'Do you really want to delete this gallery with all related content?' => 'Möchtest du wirklich diese Galerie mit allen zugehörigen Inhalten löschen?',
  'Do you really want to delete this item with all related content?' => 'Möchtest du wirklich dieses Element mit allen zugehörigen Inhalten löschen?',
  'Don\'t show the gallery snippet in this space.' => 'Das Galerie-Schnipsel in diesem Space nicht anzeigen.',
  'Download' => 'Download',
  'Edit' => 'Bearbeiten',
  'Edit Gallery' => 'Galerie bearbeiten',
  'Gallery' => 'Galerie',
  'Gallery:' => 'Galerie:',
  'In case the gallery is not visible for the current user, the snippet will use the latest accessible gallery instead.' => 'Falls die Galerie für den aktuellen Benutzer nicht sichtbar ist, verwendet das Schnipsel stattdessen die neueste zugängliche Galerie.',
  'Insufficient rights to execute this action.' => 'Unzureichende Rechte zur Durchführung dieser Aktion.',
  'Item could not be deleted!' => 'Element konnte nicht gelöscht werden!',
  'Latest Gallery - {title} ({visibility})' => 'Neueste Galerie - {title} ({visibility})',
  'Make this gallery public' => 'Diese Galerie veröffentlichen',
  'Media' => 'Medien',
  'Open Gallery' => 'Galerie öffnen',
  'Posted Media Files' => 'Gepostete Mediendateien',
  'Posted pictures' => 'Gepostete Bilder',
  'Save' => 'Speichern',
  'Settings' => 'Einstellungen',
  'Show connected post' => 'Zeige zugehörigen Post',
  'Size:' => 'Größe:',
  'There are no galleries available for this space. In order to configure the gallery snippet, please <a href="{createLink}">create</a> a new gallery' => 'Für diesen Space sind keine Galerien verfügbar. Um das Galerie-Schnipsel zu konfigurieren, <a href="%7BcreateLink%7D">erstelle</a> bitte eine neue Galerie',
  'This gallery contains all posted media files from the profile.' => 'Diese Galerie enthält alle geposteten Mediendateien aus dem Profil.',
  'This gallery contains all posted media files from the space.' => 'Diese Galerie enthält alle geposteten Mediendateien aus dem Space.',
  'This gallery contains all posted media.' => 'Diese Galerie enthält alle geposteten Mediendateien.',
  'This gallery contains all posted pictures.' => 'Diese Galerie enthält alle geposteten Bilder.',
  'Upload' => 'Hochladen',
  'added by ' => 'hinzugefügt von',
  'of posted media files' => 'von geposteten Mediendateien',
];
