<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '<strong>Add</strong> new gallery' => '<strong>Dodaj</strong> nową galeri',
  '<strong>Confirm</strong> delete gallery' => '<strong>Potwierdź</strong> usunięcie galerii',
  '<strong>Confirm</strong> delete item' => '<strong>Potwierdź</strong> usunięcie elementu',
  '<strong>Edit</strong> gallery' => '<strong>Edytuj</strong> galerię',
  '<strong>Edit</strong> media' => '<strong>Edytuj</strong> media',
  '<strong>Gallery</strong> ' => '<strong>Galeria</strong>',
  '<strong>Gallery</strong> settings' => '<strong>Ustawienia</strong> galerii',
  '<strong>List</strong> of galleries' => '<strong>Lista<strong> galerii</strong></strong>',
  'Gallery write access' => '',
  'Allows the user to add, modify images and galleries.' => '',
  'Add Gallery' => 'Dodaj galerię',
  'Adds gallery module to this space.' => 'Dodaje moduł galerii do tej strefy.',
  'Adds gallery module to your profile.' => 'Dodaje moduł galerii do Twojego profilu.',
  'Back to overview' => 'Powrót do przeglądu',
  'Choose snippet gallery' => '',
  'Click here to add new Gallery' => 'Kliknij tutaj aby dodać nową galerię',
  'Click or drop files here' => 'Kliknij lub upuść pliki tutaj',
  'Close' => 'Zamknij',
  'Delete' => 'Usuń',
  'Delete Gallery' => 'Usuń galerię',
  'Deleted' => 'Usunięto',
  'Do you really want to delete this gallery with all related content?' => 'Czy na pewno chesz usunąć tę galerię wraz z całą zawrtością?',
  'Do you really want to delete this item with all related content?' => 'Czy naprawdę chcesz usunąć ten element wraz z całą zawartością?',
  'Don\'t show the gallery snippet in this space.' => '',
  'Download' => 'Pobierz',
  'Edit' => 'Edytuj',
  'Edit Gallery' => 'Edytuj galerię',
  'Gallery' => 'Galeria',
  'Gallery:' => 'Galeria:',
  'In case the gallery is not visible for the current user, the snippet will use the latest accessible gallery instead.' => '',
  'Insufficient rights to execute this action.' => 'Brak wystarczających uprawnień do wykonania tego działania.',
  'Item could not be deleted!' => 'Element nie mógł zostać usunięty.',
  'Latest Gallery - {title} ({visibility})' => 'Ostatnia galeria - {title} ({visibility})',
  'Make this gallery public' => 'Upublicznij tę galerię',
  'Media' => 'Media',
  'Open Gallery' => '',
  'Posted Media Files' => '',
  'Posted pictures' => '',
  'Save' => 'Zapisz',
  'Settings' => 'Ustawienia',
  'Show connected post' => 'Pokaż powiązany post',
  'Size:' => 'Rozmiar:',
  'There are no galleries available for this space. In order to configure the gallery snippet, please <a href="{createLink}">create</a> a new gallery' => '',
  'This gallery contains all posted media files from the profile.' => '',
  'This gallery contains all posted media files from the space.' => '',
  'This gallery contains all posted media.' => '',
  'This gallery contains all posted pictures.' => '',
  'Upload' => 'Wczytaj',
  'added by ' => 'dodano przez',
  'of posted media files' => '',
];
